@Web_API_HostAddress = http://localhost:6000

GET {{Web_API_HostAddress}}/weatherforecast
content-type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkB3ZWJzaXRlLmNvbSIsIkRlcGFydG1lbnQiOiJIUiIsIkFkbWluIjoidHJ1ZSIsIk1hbmFnZXIiOiJ0cnVlIiwiRW1wbG95bWVudERhdGUiOiIyMDI0LTAxLTAxIiwibmJmIjoxNzEzNDkyNDg2LCJleHAiOjE3MTM0OTMwODZ9.n4diJHYkqYvmP2N9Oi1vLFEiE2wNtHmcREYHQ5RArYg


